[체스] 권순찬 2단계 미션 제출합니다.
econo-spring-2021/java-chess pull request #2
Opened 2021-08-25 13:23 UTC by Kwon770

1단계를 제가 실수로 master를 대상으로 PR을 날려서 스터디 레퍼의 master로 머지가 되었네요.. 죄송합니다.. 😭

2단계 구현하면서, 퀸을 구현할 때 제일 고민을 많이 했습니다. 퀸의 이동은 룩과 비숍의 이동을 합친 형태라 결국 이 둘의 함수를 비슷하게 사용합니다. 하지만 이미 구현된 룩과 비숍을 상속하는 것도 문제지만, 두 개 이상을 상속할 수도 없으므로 함수가 중복되는 형태로 구현되었습니다. 
1. 인터페이스를 사용하기에도 인터페이스는 일부가 구현된 형태로 사용하기 위함이 아니라 룩이나 비숍을 인터페이스로 구현할 수도 없었습니다.
2. 추상클래스로 사용하기에도 2개 이상 '상속'할 수도 없고, 추상 메소드는 일부 구현할 수도 없었습니다.

체스말들을 어떤 식으로 설계해야 퀸을 올바르게 구현할 수 있을지 모르겠네요..

2021-08-31 08:45 UTC, hotheadfactory requested changes
오답이라는 건 아니지만, 설계에 대해 한 번 더 깊이 생각해 보실 시간을 드릴게요.
이후 다시 리뷰 요청하시면 바로 Approve 드리겠습니다.

2021-08-31 08:45 UTC, hotheadfactory commented on src/main/java/Chess/controller/GameController.java
> +        int toC = args.get(1).charAt(0) - 'a';
이런 부분을 컨트롤러가 처리하기보단 뷰가 해 주는 게 어떨까요?

2021-08-31 08:45 UTC, hotheadfactory commented on src/main/java/Chess/domain/ChessBoard.java
> +    private List<List<ChessUnit>> chessBoard = new ArrayList<>();
체스판을 2차원 리스트의 형태로 구현했는데, 채스판의 index 길이는 정해져 있기 때문에 배열로 하는 게 낫지 않을까요?
리스트로 구현한 특별한 이유가 있나요?

2021-08-31 08:45 UTC, hotheadfactory commented on src/main/java/Chess/domain/ChessUnit/ChessUnitType.java
> +    KING('K', 'k'),
자바의 String이 제공하는 toUpperCase() / toLowerCase() 메소드를 활용하면 하나의 필드로 해결이 가능합니다.

2021-08-31 08:45 UTC, hotheadfactory commented on src/main/java/Chess/domain/ChessUnit/EmptyCell.java
> +public class EmptyCell extends ChessUnit {
칸이 빈 상태도 하나의 체스말로 취급하기로 한 거군요. 이러한 구현으로 인해 얻는 이점이 무엇이고 단점은 무엇일까요?

2021-09-15 00:10 UTC, Kwon770 commented on src/main/java/Chess/domain/ChessBoard.java
> +    private List<List<ChessUnit>> chessBoard = new ArrayList<>();
아니요. 특별한 이유없이 단순히 모든 배열 상태를 리스트로 선언해서 사용했습니다. 배열로 수정해보겠습니다.

2021-09-15 00:16 UTC, Kwon770 commented on src/main/java/Chess/domain/ChessUnit/EmptyCell.java
> +public class EmptyCell extends ChessUnit {
이점으로는 체스말과 관련된 모든 로직 코드에서 빈 칸인지를 확인하는 코드가 필요없으므로 코드의 통일성을 가질 수 있습니다. 
단점으로는 빈 칸의 수만큼 객체가 할당되어서 메모리가 더욱 사용된다는 것 외에는 떠오르는 단점이 없습니다. 어떤 단점이 또 있을까요?

2021-09-29 00:12 UTC, merged